### ISSUE TITLE
Weekly Scrum - December 2 (Final)

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#115]
_Template._
**What did I do last week?**

**What will I do this week?**

**What's holding me back?**

**Comment by BraedenKloke** [comment]
**What yo doin?**
- #101 

**What did you do?**
- #100 

**What's holding you back?**
Nothing at the moment.

**Comment by JackieSL1** [comment]
**What did I do last week?**
- #76 
- #106 
- #107 

**What will I do this week?**
- ?

**What's holding me back?**
N/A

**Comment by ajbalara** [comment]
**What did I do last week?**
- #111 (PR will be uploaded later today)

**What will I do this week?**
- #113 

**What's holding me back?**
N/A

**Comment by Sarvesh-Sabapathy** [comment]
What did I do last week?
- create scale question
- displayed comment responses

What will I do this week?
- #116 
- #121 

What's holding me back?
- N/A
