### ISSUE TITLE
Weekly Scrum - November 7

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#25]

**Comment by BraedenKloke** [comment]
**What have I done this week?**

**What will I do next week?**

**What is holding me back?**

**Comment by ajbalara** [comment]
What have I done this week? #6 
What will I do next week (for Milestone 1)? #26 
What is holding me back? n/a

**Comment by BraedenKloke** [comment]
@AliAbdollahian @ajbalara @JackieSL1 @Sarvesh-Sabapathy make sure to include a comment. :smile:

**Comment by JackieSL1** [comment]
**What have I done this week?**
Setup the GitHub repo and CI/CD for the app
- #1
- #2 
- #11
- #12 
- #13 
- #16 


**What will I do next week? (What will I do by Milestone 1)**
Create a DB schema - #7
Add "create new survey" functionality - #28

**What is holding me back?**

**Comment by AliAbdollahian** [comment]
What have I done this week?
- #44 implementing some features for survey page
What will I do next week? (What will I do by Milestone 1)
- #30 I will add some unit test
What is holding me back?
- time!!!
