### ISSUE TITLE
Weekly Scrum - November 14

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#34]
# Postmortem
_To complete during meeting._

**What went well?**

**What did not go well?**

**What changes can we implement?**

# Comment template

**What did I do last week?**

**What will I do this week?**

**What's holding me back?**

**Comment by ajbalara** [comment]
What did I do last week?

- #26 
- #14 

What will I do this week?
- #56 

What's holding me back?

**Comment by AliAbdollahian** [comment]
What did I do last week?
- #28 
- worked on user authentication

What will I do this week?
 - #63 
 - Add tests 

What's holding me back?
- how would I simplify user authentication / incremental steps

**Comment by Sarvesh-Sabapathy** [comment]
What did I do last week?
- #46 

What will I do this week?
- add rating questions 
- #23 

What's holding me back?
- N/A
