### ISSUE TITLE
Weekly Scrum - October 31 🎃

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#5]
- what have I done this week? (with link(s) to the relevant GitHub Issue(s))
- what will I do next week? (with link(s) to the relevant GitHub Issue(s))
- what is holding me back? (if applicable)

Expected length: 1-2 sentences per item.

**Comment by BraedenKloke** [comment]
What have I done this week?

What will I do next week?

What is holding me back?

**Comment by JackieSL1** [comment]
What have I done this week?

What will I do next week?

What is holding me back?

**Comment by ajbalara** [comment]
What have I done this week? 

What will I do next week?

- Investigate survey monkey - Investigate Survey Monkey #6

What is holding me back?

**Comment by Sarvesh-Sabapathy** [comment]
What have I done this week?
n/a

What will I do next week?

- #8 

What is holding me back?
n/a

**Comment by AliAbdollahian** [comment]
What have I done this week?
n/a

What will I do next week?

- investigating survey monkey 
- research on firebase for our database 

What is holding me back?
n/a
