### ISSUE TITLE
Milestone 1: Create DB schema

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#7]

**Comment by BraedenKloke** [comment]
# Suggestion for Initial DB Schema

**Table 1: Users**
* userID (PK)
* username (unique)
* password


**Table 2: Surveys**
* ownerID (FK)
* surveyID (PK)
* title

**Table 3: Questions**
Since a survey can have an arbitrary number of questions,
we should probably have a separate table just for questions.

It may be worth having a separate table for each **type** of question. 
For example:

**Table 3.1: Comment Box Questions**
* surveyID (FK)
* comment String

**Comment by BraedenKloke** [comment]
TODO Responses table

**Comment by BraedenKloke** [comment]
# DB Schema V1
Initial DB schema designed by @JackieSL1.


![Image](https://github.com/user-attachments/assets/25b3c1b0-e7f7-4152-a441-131cb4a96d1c)

# DB Schema V2
Here is my proposal for our initial schema for Milestone 1.

I've simplified Jackie's design slightly by making the following changes:
- **Added `question` attribute to `questions` table.** This attribute represents what question the survey is prompting the user with. For example, do you like pineapple on pizza?
- **Consolidated `text responses` to a single table.** There is no need to have a separate table for `text questions` since all questions will have a question. (See previous bullet-point)
- **Removed PK from `text responses`.** Text responses is a weak entity. PK is not necessary.
- **Changed attribute `name` to `title` in `surveys` table.** Also added a default value of `"Untitled"`.
- **Removed `range` and `multiple_choice` tables for now.** These are not needed for M1. My gut says it would be wise to hold off on designing them until we are deeper into the project.


![Image](https://github.com/user-attachments/assets/7a16ea26-b1cf-4fd0-84d8-d861d310d923)

# Next Steps
1. Finalize schema for M1
2. Run test queries to verify our schema

## Test Running Queries on Schema
We should try running some queries on our schema to make sure it makes sense.

**Example Queries:**
- What are the surveys owned by a user?
- What are the questions for a survey?
- Save response to a survey.
- What are the responses for a survey?

**Comment by JackieSL1** [comment]
Changes look great Braeden! I think it's a good idea to [only include what we need for now](https://en.wikipedia.org/wiki/You_aren%27t_gonna_need_it). Two questions:

I don't entirely understand removing the PK from `Text Responses` . As a 1-to-many relation, won't need some unique ID along with the `surveyID`?

Also, I mentioned this to you yesterday, but we'll need to include a way to store unique survey links, but we can add this when we actually implement the feature.

**Comment by BraedenKloke** [comment]
I was wrong to remove PK from `Text Responses`. I've added it back in.

Yes. We may need someway of storing a unique survey link in the future.
