### ISSUE TITLE
Weekly Scum - November 21

### ISSUE THREAD

**Issue by BraedenKloke** [JackieSL1/mini-survey-monkey#78]
_Template._
**What did I do last week?**

**What will I do this week?**

**What's holding me back?**

**Comment by BraedenKloke** [comment]
**What did I do last week?**
- #53 
- Add dummy login page (anyone can login)
- Add signup page

** What will I do this week?**
- #53 
- feat: log in users that exist
- feat: display surveys for logged in user

**What's holding me back?**
- Not sure how to design a 'logged in' user.

**Comment by ajbalara** [comment]
**What did I do last week?**

- #62 
- #58 

**What will I do this week**

- #24 
- #32 

**What is holding me back**
N/A

**Comment by JackieSL1** [comment]
**What did I do last week?** 
- #60 
- #61 

**What will I do this week**

- Add ability to collect responses

**What is holding me back**
N/A

**Comment by Sarvesh-Sabapathy** [comment]
What did I do last week?
- worked on #21 

What will I do this week
- finish #21 
- update database schema and create tests for scale questions
- #23 

What is holding me back
N/A

**Comment by AliAbdollahian** [comment]
What did I do last week?
- #22 
- #51 
- #96 

What will I do this week?
- working on presentation 

What's holding me back?
N/A
